<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: rignonnoel
 * Date: Mon, 14 Sep 2015 16:34:30 -0400
 */

$conf['title'] = 'MLL_Wiki';
$conf['lang'] = 'fr';
$conf['template'] = 'writr';
$conf['tagline'] = 'Le wiki de la Maison du Logiciel Libre';
$conf['license'] = 'cc-zero';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile,profile_delete';
$conf['userewrite'] = '2';
$conf['plugin']['translation']['translations'] = 'en fr';
$conf['plugin']['translation']['dropdown'] = 1;
$conf['plugin']['translation']['display'] = 'name,title';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['localabout'] = 1;

// end auto-generated content
